// Problem URLs categorized by difficulty and website
const problemUrls = {
  LeetCode: {
    Easy: [
      'https://leetcode.com/problems/two-sum/',
      'https://leetcode.com/problems/palindrome-number/',
      'https://leetcode.com/problems/roman-to-integer/',
      'https://leetcode.com/problems/longest-common-prefix/',
      'https://leetcode.com/problems/valid-parentheses/',
      'https://leetcode.com/problems/merge-two-sorted-lists/',
      'https://leetcode.com/problems/remove-duplicates-from-sorted-array/',
      'https://leetcode.com/problems/remove-element/',
      'https://leetcode.com/problems/length-of-last-word/',
      'https://leetcode.com/problems/plus-one/',
      'https://leetcode.com/problems/add-binary/',
      'https://leetcode.com/problems/climbing-stairs/',
      'https://leetcode.com/problems/remove-duplicates-from-sorted-list/',
      'https://leetcode.com/problems/merge-sorted-array/',
      'https://leetcode.com/problems/same-tree/',
      'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
      'https://leetcode.com/problems/symmetric-tree/',
      'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/',
      'https://leetcode.com/problems/balanced-binary-tree/',
      'https://leetcode.com/problems/minimum-depth-of-binary-tree/',
      'https://leetcode.com/problems/path-sum/',
      'https://leetcode.com/problems/pascals-triangle/',
      'https://leetcode.com/problems/pascals-triangle-ii/',
      'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
      'https://leetcode.com/problems/valid-palindrome/',
      'https://leetcode.com/problems/single-number/',
      'https://leetcode.com/problems/linked-list-cycle/',
      'https://leetcode.com/problems/intersection-of-two-linked-lists/',
      'https://leetcode.com/problems/excel-sheet-column-title/',
      'https://leetcode.com/problems/majority-element/',
      'https://leetcode.com/problems/excel-sheet-column-number/',
      'https://leetcode.com/problems/reverse-bits/',
      'https://leetcode.com/problems/number-of-1-bits/',
      'https://leetcode.com/problems/happy-number/',
      'https://leetcode.com/problems/remove-linked-list-elements/',
      'https://leetcode.com/problems/implement-strstr/',
      'https://leetcode.com/problems/sqrtx/',
      'https://leetcode.com/problems/reverse-linked-list/',
    ],
    Medium: [
      'https://leetcode.com/problems/reverse-integer/',
      'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/',
      'https://leetcode.com/problems/binary-tree-level-order-traversal/',
      'https://leetcode.com/problems/add-two-numbers/',
      'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
      'https://leetcode.com/problems/valid-sudoku/',
      'https://leetcode.com/problems/jump-game/',
      'https://leetcode.com/problems/jump-game-ii/',
      'https://leetcode.com/problems/permutations/',
      'https://leetcode.com/problems/permutations-ii/',
      'https://leetcode.com/problems/rotate-image/',
      'https://leetcode.com/problems/group-anagrams/',
      'https://leetcode.com/problems/powx-n/',
      'https://leetcode.com/problems/maximum-subarray/',
      'https://leetcode.com/problems/spiral-matrix/',
      'https://leetcode.com/problems/spiral-matrix-ii/',
      'https://leetcode.com/problems/unique-paths/',
      'https://leetcode.com/problems/unique-paths-ii/',
      'https://leetcode.com/problems/minimum-path-sum/',
      'https://leetcode.com/problems/plus-one-linked-list/',
      'https://leetcode.com/problems/simplify-path/',
      'https://leetcode.com/problems/set-matrix-zeroes/',
      'https://leetcode.com/problems/search-a-2d-matrix/',
      'https://leetcode.com/problems/sort-colors/',
      'https://leetcode.com/problems/combination-sum/',
      'https://leetcode.com/problems/combination-sum-ii/',
      'https://leetcode.com/problems/multiply-strings/',
      'https://leetcode.com/problems/rotate-list/',
      'https://leetcode.com/problems/partition-list/',
      'https://leetcode.com/problems/merge-intervals/',
      'https://leetcode.com/problems/insert-interval/',
      'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',
      'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
      'https://leetcode.com/problems/4sum/',
      'https://leetcode.com/problems/generate-parentheses/',
      'https://leetcode.com/problems/swap-nodes-in-pairs/',
      'https://leetcode.com/problems/divide-two-integers/',
      'https://leetcode.com/problems/next-permutation/',
      'https://leetcode.com/problems/search-in-rotated-sorted-array/',
      'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/',
    ],
    Hard: [
      'https://leetcode.com/problems/median-of-two-sorted-arrays/',
      'https://leetcode.com/problems/regular-expression-matching/',
      'https://leetcode.com/problems/merge-k-sorted-lists/',
      'https://leetcode.com/problems/reverse-nodes-in-k-group/',
      'https://leetcode.com/problems/sudoku-solver/',
      'https://leetcode.com/problems/first-missing-positive/',
      'https://leetcode.com/problems/trapping-rain-water/',
      'https://leetcode.com/problems/n-queens/',
      'https://leetcode.com/problems/n-queens-ii/',
      'https://leetcode.com/problems/valid-number/',
      'https://leetcode.com/problems/text-justification/',
      'https://leetcode.com/problems/edit-distance/',
      'https://leetcode.com/problems/minimum-window-substring/',
      'https://leetcode.com/problems/length-of-longest-substring/',
      'https://leetcode.com/problems/substring-with-concatenation-of-all-words/',
      'https://leetcode.com/problems/longest-valid-parentheses/',
      'https://leetcode.com/problems/count-and-say/',
      'https://leetcode.com/problems/reverse-words-in-a-string/',
      'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',
      'https://leetcode.com/problems/min-stack/',
    ],
  },
  HackerRank: {
    Easy: [
      'https://www.hackerrank.com/challenges/solve-me-first/problem',
      'https://www.hackerrank.com/challenges/simple-array-sum/problem',
      'https://www.hackerrank.com/challenges/compare-the-triplets/problem',
      'https://www.hackerrank.com/challenges/a-very-big-sum/problem',
      'https://www.hackerrank.com/challenges/diagonal-difference/problem',
      'https://www.hackerrank.com/challenges/plus-minus/problem',
      'https://www.hackerrank.com/challenges/staircase/problem',
      'https://www.hackerrank.com/challenges/mini-max-sum/problem',
      'https://www.hackerrank.com/challenges/birthday-cake-candles/problem',
      'https://www.hackerrank.com/challenges/time-conversion/problem',
      'https://www.hackerrank.com/challenges/apple-and-orange/problem',
      'https://www.hackerrank.com/challenges/kangaroo/problem',
      'https://www.hackerrank.com/challenges/between-two-sets/problem',
      'https://www.hackerrank.com/challenges/divisible-sum-pairs/problem',
      'https://www.hackerrank.com/challenges/migratory-birds/problem',
      'https://www.hackerrank.com/challenges/day-of-the-programmer/problem',
      'https://www.hackerrank.com/challenges/bon-appetit/problem',
      'https://www.hackerrank.com/challenges/sock-merchant/problem',
      'https://www.hackerrank.com/challenges/counting-valleys/problem',
      'https://www.hackerrank.com/challenges/electronics-shop/problem',
      'https://www.hackerrank.com/challenges/cats-and-a-mouse/problem',
      'https://www.hackerrank.com/challenges/magic-square-forming/problem',
      'https://www.hackerrank.com/challenges/picking-numbers/problem',
      'https://www.hackerrank.com/challenges/climbing-the-leaderboard/problem',
      'https://www.hackerrank.com/challenges/the-hurdle-race/problem',
      'https://www.hackerrank.com/challenges/designer-pdf-viewer/problem',
      'https://www.hackerrank.com/challenges/utopian-tree/problem',
      'https://www.hackerrank.com/challenges/angry-professor/problem',
      'https://www.hackerrank.com/challenges/beautiful-days-at-the-movies/problem',
      'https://www.hackerrank.com/challenges/save-the-prisoner/problem',
      'https://www.hackerrank.com/challenges/circular-array-rotation/problem',
      'https://www.hackerrank.com/challenges/permutation-equation/problem',
      'https://www.hackerrank.com/challenges/jumping-on-the-clouds-revisited/problem',
      'https://www.hackerrank.com/challenges/find-digits/problem',
      'https://www.hackerrank.com/challenges/append-and-delete/problem',
    ],
    Medium: [
      'https://www.hackerrank.com/challenges/the-time-in-words/problem',
      'https://www.hackerrank.com/challenges/encryption/problem',
      'https://www.hackerrank.com/challenges/bigger-is-greater/problem',
      'https://www.hackerrank.com/challenges/absolute-permutation/problem',
      'https://www.hackerrank.com/challenges/the-grid-search/problem',
      'https://www.hackerrank.com/challenges/maxsubarray/problem',
      'https://www.hackerrank.com/challenges/coin-change/problem',
      'https://www.hackerrank.com/challenges/sherlock-and-anagrams/problem',
      'https://www.hackerrank.com/challenges/common-child/problem',
      'https://www.hackerrank.com/challenges/matrix-rotation-algo/problem',
      'https://www.hackerrank.com/challenges/maximum-element/problem',
      'https://www.hackerrank.com/challenges/the-power-sum/problem',
      'https://www.hackerrank.com/challenges/maximum-perimeter-triangle/problem',
      'https://www.hackerrank.com/challenges/jumping-on-the-clouds/problem',
      'https://www.hackerrank.com/challenges/minimum-loss/problem',
      'https://www.hackerrank.com/challenges/greedy-florist/problem',
      'https://www.hackerrank.com/challenges/max-array-sum/problem',
      'https://www.hackerrank.com/challenges/equal-stacks/problem',
      'https://www.hackerrank.com/challenges/queens-attack-2/problem',
      'https://www.hackerrank.com/challenges/organizing-containers-of-balls/problem',
      'https://www.hackerrank.com/challenges/two-pluses/problem',
      'https://www.hackerrank.com/challenges/larrys-array/problem',
      'https://www.hackerrank.com/challenges/almost-sorted/problem',
      'https://www.hackerrank.com/challenges/candies/problem',
      'https://www.hackerrank.com/challenges/stockmax/problem',
      'https://www.hackerrank.com/challenges/pairs/problem',
      'https://www.hackerrank.com/challenges/separate-the-numbers/problem',
      'https://www.hackerrank.com/challenges/marcs-cakewalk/problem',
      'https://www.hackerrank.com/challenges/two-arrays/problem',
      'https://www.hackerrank.com/challenges/castle-on-the-grid/problem',
      'https://www.hackerrank.com/challenges/balanced-brackets/problem',
      'https://www.hackerrank.com/challenges/counter-game/problem',
      'https://www.hackerrank.com/challenges/icecream-parlor/problem',
      'https://www.hackerrank.com/challenges/knightl-on-chessboard/problem',
      'https://www.hackerrank.com/challenges/new-year-chaos/problem',
      'https://www.hackerrank.com/challenges/lilys-homework/problem',
      'https://www.hackerrank.com/challenges/gridland-metro/problem',
    ],
    Hard: [
      'https://www.hackerrank.com/challenges/matrix-rotation-algo/problem',
      'https://www.hackerrank.com/challenges/coin-change/problem',
      'https://www.hackerrank.com/challenges/sherlock-and-anagrams/problem',
      'https://www.hackerrank.com/challenges/common-child/problem',
      'https://www.hackerrank.com/challenges/maxsubarray/problem',
      'https://www.hackerrank.com/challenges/kingdom-division/problem',
      'https://www.hackerrank.com/challenges/ctci-recursive-staircase/problem',
      'https://www.hackerrank.com/challenges/travel-around-the-world/problem',
      'https://www.hackerrank.com/challenges/floyd-city-of-blinding-lights/problem',
      'https://www.hackerrank.com/challenges/sam-and-substrings/problem',
      'https://www.hackerrank.com/challenges/connected-cell-in-a-grid/problem',
      'https://www.hackerrank.com/challenges/maximum-subarray-sum/problem',
      'https://www.hackerrank.com/challenges/frequency-queries/problem',
      'https://www.hackerrank.com/challenges/sherlock-and-cost/problem',
      'https://www.hackerrank.com/challenges/count-strings/problem',
      'https://www.hackerrank.com/challenges/red-john-is-back/problem',
      'https://www.hackerrank.com/challenges/dynamic-programming-classics-the-longest-common-subsequence/problem',
      'https://www.hackerrank.com/challenges/substring-diff/problem',
      'https://www.hackerrank.com/challenges/hexagonal-grid/problem',
      'https://www.hackerrank.com/challenges/swap-nodes-algo/problem',
      'https://www.hackerrank.com/challenges/square-ten-tree/problem',
      'https://www.hackerrank.com/challenges/dijkstrashortreach/problem',
      'https://www.hackerrank.com/challenges/tree-huffman-decoding/problem',
      'https://www.hackerrank.com/challenges/tree-level-order-traversal/problem',
      'https://www.hackerrank.com/challenges/binary-search-tree-insertion/problem',
      'https://www.hackerrank.com/challenges/tree-height-of-a-binary-tree/problem',
      'https://www.hackerrank.com/challenges/tree-top-view/problem',
      'https://www.hackerrank.com/challenges/tree-inorder-traversal/problem',
      'https://www.hackerrank.com/challenges/tree-preorder-traversal/problem',
      'https://www.hackerrank.com/challenges/tree-postorder-traversal/problem',
      'https://www.hackerrank.com/challenges/self-balancing-tree/problem',
      'https://www.hackerrank.com/challenges/median/problem',
      'https://www.hackerrank.com/challenges/reduced-string/problem',
    ],
  },
  Codingame: {
    Easy: [
      'https://www.codingame.com/training/easy/power-of-thor-episode-1',
      'https://www.codingame.com/training/easy/the-descent',
      'https://www.codingame.com/training/easy/horse-racing-duals',
      'https://www.codingame.com/training/easy/chuck-norris',
      'https://www.codingame.com/training/easy/ascii-art',
      'https://www.codingame.com/training/easy/mars-lander-episode-1',
      'https://www.codingame.com/training/easy/temperatures',
      'https://www.codingame.com/training/easy/defibrillators',
      'https://www.codingame.com/training/easy/mime-type',
      'https://www.codingame.com/training/easy/onboarding',
      'https://www.codingame.com/training/easy/ghost-legs',
      'https://www.codingame.com/training/easy/brackets-extreme-edition',
      'https://www.codingame.com/training/easy/hunger-games',
      'https://www.codingame.com/training/easy/lumen',
      'https://www.codingame.com/training/easy/retro-typewriter-art',
      'https://www.codingame.com/training/easy/organic-compounds',
      'https://www.codingame.com/training/easy/1d-spreadsheet',
      'https://www.codingame.com/training/easy/brick-in-the-wall',
      'https://www.codingame.com/training/easy/dwarfs-standing-on-the-shoulders-of-giants',
      'https://www.codingame.com/training/easy/blowing-fuse',
      'https://www.codingame.com/training/easy/death-first-search-episode-1',
      'https://www.codingame.com/training/easy/credit-card-verifier-luhns-algorithm',
      'https://www.codingame.com/training/easy/container-terminal',
      'https://www.codingame.com/training/easy/rugby-score',
      'https://www.codingame.com/training/easy/equivalent-resistance-circuit-building',
      'https://www.codingame.com/training/easy/encryptiondecryption-of-enigma-machine',
      'https://www.codingame.com/training/easy/detective-pikaptcha-ep1',
      'https://www.codingame.com/training/easy/simple-ai-duel',
      'https://www.codingame.com/training/easy/reverse-fizzbuzz',
      'https://www.codingame.com/training/easy/happy-numbers',
      'https://www.codingame.com/training/easy/bank-robbers',
      'https://www.codingame.com/training/easy/isbn-check-digit',
      'https://www.codingame.com/training/easy/unit-fractions',
      'https://www.codingame.com/training/easy/horse-racing-hyperduals',
      'https://www.codingame.com/training/easy/die-hard',
      'https://www.codingame.com/training/easy/addem-up',
      'https://www.codingame.com/training/easy/tic-tac-toe',
      'https://www.codingame.com/training/easy/rubik',
      'https://www.codingame.com/training/easy/rock-paper-scissors-lizard-spock',
      'https://www.codingame.com/training/easy/brick-breaker',
    ],
    Medium: [
      'https://www.codingame.com/training/medium/shadows-of-the-knight-episode-1',
      'https://www.codingame.com/training/medium/there-is-no-spoon-episode-1',
      'https://www.codingame.com/training/medium/skynet-revolution-episode-1',
      'https://www.codingame.com/training/medium/winamax-battle',
      'https://www.codingame.com/training/medium/the-gift',
      'https://www.codingame.com/training/medium/stock-exchange-losses',
      'https://www.codingame.com/training/medium/telephone-numbers',
      'https://www.codingame.com/training/medium/dwarfs-standing-on-the-shoulders-of-giants',
      'https://www.codingame.com/training/medium/the-paranoid-android',
      'https://www.codingame.com/training/medium/conway-sequence',
      'https://www.codingame.com/training/medium/scrabble',
      'https://www.codingame.com/training/medium/war',
      'https://www.codingame.com/training/medium/aneo',
      'https://www.codingame.com/training/medium/brackets-extreme-edition',
      'https://www.codingame.com/training/medium/bender-episode-1',
      'https://www.codingame.com/training/medium/the-last-crusade-episode-1',
      'https://www.codingame.com/training/medium/death-first-search-episode-2',
      'https://www.codingame.com/training/medium/network-cabling',
      'https://www.codingame.com/training/medium/rectangle-partition',
      'https://www.codingame.com/training/medium/surface',
      'https://www.codingame.com/training/medium/vox-codei-episode-1',
      'https://www.codingame.com/training/medium/mayan-calculation',
      'https://www.codingame.com/training/medium/the-great-escape',
      'https://www.codingame.com/training/medium/roller-coaster',
      'https://www.codingame.com/training/medium/1d-spreadsheet',
      'https://www.codingame.com/training/medium/detective-pikaptcha-ep2',
      'https://www.codingame.com/training/medium/minesweeper',
      'https://www.codingame.com/training/medium/rubik',
      'https://www.codingame.com/training/medium/simple-ai-duel',
      'https://www.codingame.com/training/medium/reverse-fizzbuzz',
      'https://www.codingame.com/training/medium/happy-numbers',
      'https://www.codingame.com/training/medium/bank-robbers',
      'https://www.codingame.com/training/medium/isbn-check-digit',
      'https://www.codingame.com/training/medium/unit-fractions',
      'https://www.codingame.com/training/medium/horse-racing-hyperduals',
      'https://www.codingame.com/training/medium/die-hard',
      'https://www.codingame.com/training/medium/addem-up',
      'https://www.codingame.com/training/medium/tic-tac-toe',
      'https://www.codingame.com/training/medium/brick-breaker',
      'https://www.codingame.com/training/medium/music-scores',
    ],
    Hard: [
      'https://www.codingame.com/training/hard/shadows-of-the-knight-episode-2',
      'https://www.codingame.com/training/hard/skynet-revolution-episode-2',
      'https://www.codingame.com/training/hard/there-is-no-spoon-episode-2',
      'https://www.codingame.com/training/hard/the-last-crusade-episode-2',
      'https://www.codingame.com/training/hard/vox-codei-episode-2',
      'https://www.codingame.com/training/hard/super-computer',
      'https://www.codingame.com/training/hard/roller-coaster',
      'https://www.codingame.com/training/hard/genome-sequencing',
      'https://www.codingame.com/training/hard/bender-episode-2',
      'https://www.codingame.com/training/hard/cg-log',
      'https://www.codingame.com/training/hard/surface',
      'https://www.codingame.com/training/hard/music-scores',
      'https://www.codingame.com/training/hard/winamax-sponsored-contest',
      'https://www.codingame.com/training/hard/the-paranoid-android',
      'https://www.codingame.com/training/hard/aneo-sponsored-puzzle',
      'https://www.codingame.com/training/hard/the-great-escape',
      'https://www.codingame.com/training/hard/minesweeper',
      'https://www.codingame.com/training/hard/tan-network',
      'https://www.codingame.com/training/hard/bulls-and-cows',
      'https://www.codingame.com/training/hard/cgx-formatter',
      'https://www.codingame.com/training/hard/number-shifting',
      'https://www.codingame.com/training/hard/teads-sponsored-contest',
      'https://www.codingame.com/training/hard/the-labyrinth',
      'https://www.codingame.com/training/hard/tic-tac-toe',
      'https://www.codingame.com/training/hard/dwarfs-standing-on-the-shoulders-of-giants',
      'https://www.codingame.com/training/hard/2048',
      'https://www.codingame.com/training/hard/simple-ai-duel',
      'https://www.codingame.com/training/hard/reverse-fizzbuzz',
      'https://www.codingame.com/training/hard/happy-numbers',
      'https://www.codingame.com/training/hard/bank-robbers',
      'https://www.codingame.com/training/hard/isbn-check-digit',
      'https://www.codingame.com/training/hard/unit-fractions',
      'https://www.codingame.com/training/hard/horse-racing-hyperduals',
      'https://www.codingame.com/training/hard/die-hard',
      'https://www.codingame.com/training/hard/addem-up',
      'https://www.codingame.com/training/hard/rubik',
      'https://www.codingame.com/training/hard/rock-paper-scissors-lizard-spock',
      'https://www.codingame.com/training/hard/brick-breaker',
      'https://www.codingame.com/training/hard/winamax-battle',
      'https://www.codingame.com/training/hard/the-gift',
    ],
  },
  AtCoder: {
    Easy: [
      'https://atcoder.jp/contests/abc086/tasks/abc086_a',
      'https://atcoder.jp/contests/abc081/tasks/abc081_a',
      'https://atcoder.jp/contests/abc083/tasks/abc083_a',
      'https://atcoder.jp/contests/abc085/tasks/abc085_a',
      'https://atcoder.jp/contests/abc087/tasks/abc087_a',
      'https://atcoder.jp/contests/abc089/tasks/abc089_a',
      'https://atcoder.jp/contests/abc091/tasks/abc091_a',
      'https://atcoder.jp/contests/abc093/tasks/abc093_a',
      'https://atcoder.jp/contests/abc095/tasks/abc095_a',
      'https://atcoder.jp/contests/abc097/tasks/abc097_a',
      'https://atcoder.jp/contests/abc099/tasks/abc099_a',
      'https://atcoder.jp/contests/abc101/tasks/abc101_a',
      'https://atcoder.jp/contests/abc103/tasks/abc103_a',
      'https://atcoder.jp/contests/abc105/tasks/abc105_a',
      'https://atcoder.jp/contests/abc107/tasks/abc107_a',
      'https://atcoder.jp/contests/abc109/tasks/abc109_a',
      'https://atcoder.jp/contests/abc111/tasks/abc111_a',
      'https://atcoder.jp/contests/abc113/tasks/abc113_a',
      'https://atcoder.jp/contests/abc115/tasks/abc115_a',
      'https://atcoder.jp/contests/abc117/tasks/abc117_a',
      'https://atcoder.jp/contests/abc119/tasks/abc119_a',
      'https://atcoder.jp/contests/abc121/tasks/abc121_a',
      'https://atcoder.jp/contests/abc123/tasks/abc123_a',
      'https://atcoder.jp/contests/abc125/tasks/abc125_a',
      'https://atcoder.jp/contests/abc127/tasks/abc127_a',
      'https://atcoder.jp/contests/abc129/tasks/abc129_a',
      'https://atcoder.jp/contests/abc131/tasks/abc131_a',
      'https://atcoder.jp/contests/abc133/tasks/abc133_a',
      'https://atcoder.jp/contests/abc135/tasks/abc135_a',
      'https://atcoder.jp/contests/abc137/tasks/abc137_a',
      'https://atcoder.jp/contests/abc139/tasks/abc139_a',
      'https://atcoder.jp/contests/abc141/tasks/abc141_a',
      'https://atcoder.jp/contests/abc143/tasks/abc143_a',
      'https://atcoder.jp/contests/abc145/tasks/abc145_a',
      'https://atcoder.jp/contests/abc147/tasks/abc147_a',
      'https://atcoder.jp/contests/abc149/tasks/abc149_a',
      'https://atcoder.jp/contests/abc151/tasks/abc151_a',
      'https://atcoder.jp/contests/abc153/tasks/abc153_a',
      'https://atcoder.jp/contests/abc155/tasks/abc155_a',
      'https://atcoder.jp/contests/abc157/tasks/abc157_a',
    ],
    Medium: [
      'https://atcoder.jp/contests/abc081/tasks/abc081_b',
      'https://atcoder.jp/contests/abc083/tasks/abc083_b',
      'https://atcoder.jp/contests/abc085/tasks/abc085_b',
      'https://atcoder.jp/contests/abc087/tasks/abc087_b',
      'https://atcoder.jp/contests/abc089/tasks/abc089_b',
      'https://atcoder.jp/contests/abc091/tasks/abc091_b',
      'https://atcoder.jp/contests/abc093/tasks/abc093_b',
      'https://atcoder.jp/contests/abc095/tasks/abc095_b',
      'https://atcoder.jp/contests/abc097/tasks/abc097_b',
      'https://atcoder.jp/contests/abc099/tasks/abc099_b',
      'https://atcoder.jp/contests/abc101/tasks/abc101_b',
      'https://atcoder.jp/contests/abc103/tasks/abc103_b',
      'https://atcoder.jp/contests/abc105/tasks/abc105_b',
      'https://atcoder.jp/contests/abc107/tasks/abc107_b',
      'https://atcoder.jp/contests/abc109/tasks/abc109_b',
      'https://atcoder.jp/contests/abc111/tasks/abc111_b',
      'https://atcoder.jp/contests/abc113/tasks/abc113_b',
      'https://atcoder.jp/contests/abc115/tasks/abc115_b',
      'https://atcoder.jp/contests/abc117/tasks/abc117_b',
      'https://atcoder.jp/contests/abc119/tasks/abc119_b',
      'https://atcoder.jp/contests/abc121/tasks/abc121_b',
      'https://atcoder.jp/contests/abc123/tasks/abc123_b',
      'https://atcoder.jp/contests/abc125/tasks/abc125_b',
      'https://atcoder.jp/contests/abc127/tasks/abc127_b',
      'https://atcoder.jp/contests/abc129/tasks/abc129_b',
      'https://atcoder.jp/contests/abc131/tasks/abc131_b',
      'https://atcoder.jp/contests/abc133/tasks/abc133_b',
      'https://atcoder.jp/contests/abc135/tasks/abc135_b',
      'https://atcoder.jp/contests/abc137/tasks/abc137_b',
      'https://atcoder.jp/contests/abc139/tasks/abc139_b',
      'https://atcoder.jp/contests/abc141/tasks/abc141_b',
      'https://atcoder.jp/contests/abc143/tasks/abc143_b',
      'https://atcoder.jp/contests/abc145/tasks/abc145_b',
      'https://atcoder.jp/contests/abc147/tasks/abc147_b',
      'https://atcoder.jp/contests/abc149/tasks/abc149_b',
      'https://atcoder.jp/contests/abc151/tasks/abc151_b',
      'https://atcoder.jp/contests/abc153/tasks/abc153_b',
      'https://atcoder.jp/contests/abc155/tasks/abc155_b',
      'https://atcoder.jp/contests/abc157/tasks/abc157_b',
      'https://atcoder.jp/contests/abc159/tasks/abc159_b',
    ],
    Hard: [
      'https://atcoder.jp/contests/abc088/tasks/abc088_b',
      'https://atcoder.jp/contests/arc086/tasks/arc086_a',
      'https://atcoder.jp/contests/arc089/tasks/arc089_a',
      'https://atcoder.jp/contests/arc091/tasks/arc091_a',
      'https://atcoder.jp/contests/arc093/tasks/arc093_a',
      'https://atcoder.jp/contests/arc095/tasks/arc095_a',
      'https://atcoder.jp/contests/arc097/tasks/arc097_a',
      'https://atcoder.jp/contests/arc099/tasks/arc099_a',
      'https://atcoder.jp/contests/arc101/tasks/arc101_a',
      'https://atcoder.jp/contests/arc103/tasks/arc103_a',
      'https://atcoder.jp/contests/arc105/tasks/arc105_a',
      'https://atcoder.jp/contests/arc107/tasks/arc107_a',
      'https://atcoder.jp/contests/arc109/tasks/arc109_a',
      'https://atcoder.jp/contests/arc111/tasks/arc111_a',
      'https://atcoder.jp/contests/arc113/tasks/arc113_a',
      'https://atcoder.jp/contests/arc115/tasks/arc115_a',
      'https://atcoder.jp/contests/arc117/tasks/arc117_a',
      'https://atcoder.jp/contests/arc119/tasks/arc119_a',
      'https://atcoder.jp/contests/arc121/tasks/arc121_a',
      'https://atcoder.jp/contests/arc123/tasks/arc123_a',
      'https://atcoder.jp/contests/arc125/tasks/arc125_a',
      'https://atcoder.jp/contests/arc127/tasks/arc127_a',
      'https://atcoder.jp/contests/arc129/tasks/arc129_a',
      'https://atcoder.jp/contests/arc131/tasks/arc131_a',
      'https://atcoder.jp/contests/arc133/tasks/arc133_a',
      'https://atcoder.jp/contests/arc135/tasks/arc135_a',
      'https://atcoder.jp/contests/arc137/tasks/arc137_a',
      'https://atcoder.jp/contests/arc139/tasks/arc139_a',
      'https://atcoder.jp/contests/arc141/tasks/arc141_a',
      'https://atcoder.jp/contests/arc143/tasks/arc143_a',
      'https://atcoder.jp/contests/arc145/tasks/arc145_a',
      'https://atcoder.jp/contests/arc147/tasks/arc147_a',
      'https://atcoder.jp/contests/arc149/tasks/arc149_a',
      'https://atcoder.jp/contests/arc151/tasks/arc151_a',
      'https://atcoder.jp/contests/arc153/tasks/arc153_a',
      'https://atcoder.jp/contests/arc155/tasks/arc155_a',
      'https://atcoder.jp/contests/arc157/tasks/arc157_a',
      'https://atcoder.jp/contests/arc159/tasks/arc159_a',
      'https://atcoder.jp/contests/arc161/tasks/arc161_a',
      'https://atcoder.jp/contests/arc163/tasks/arc163_a',
    ],
  },
};

// Pre-compute the "All" list for default behavior
const allProblems = Object.keys(problemUrls).reduce((acc, site) => {
  return acc.concat(
    problemUrls[site].Easy || [],
    problemUrls[site].Medium || [],
    problemUrls[site].Hard || [],
  );
}, []);

// Function to get filtered problem list based on difficulty and website
function getFilteredProblems(difficulty, website) {
  let filtered = [];

  // Handle website filter
  const websites = website === 'All' ? Object.keys(problemUrls) : [website];

  // Handle difficulty filter
  websites.forEach((site) => {
    if (!problemUrls[site]) {
      console.error(`Website "${site}" not found in problemUrls`);
      return; // Skip if site doesn't exist
    }
    if (difficulty === 'All') {
      filtered = filtered.concat(
        problemUrls[site].Easy || [],
        problemUrls[site].Medium || [],
        problemUrls[site].Hard || [],
      );
    } else {
      filtered = filtered.concat(problemUrls[site][difficulty] || []);
    }
  });

  return filtered.length > 0 ? filtered : allProblems; // Fallback to all if empty
}

// Function to pick a random URL from filtered list
function getRandomProblemUrl(difficulty, website) {
  const filteredProblems = getFilteredProblems(difficulty, website);
  if (filteredProblems.length === 0) {
    console.error('No problems found for selection, using fallback');
    return 'https://leetcode.com/problems/two-sum/'; // Absolute fallback
  }
  const randomIndex = Math.floor(Math.random() * filteredProblems.length);
  return filteredProblems[randomIndex];
}

// Redirect logic with stored preferences
browser.webRequest.onBeforeRequest.addListener(
  function (details) {
    return new Promise((resolve) => {
      browser.storage.sync.get(
        ['difficulty', 'website', 'enabled'],
        function (data) {
          if (data.enabled === false) {
            resolve({}); // No redirect
          } else {
            const difficulty = data.difficulty || 'All';
            const website = data.website || 'All';
            const redirectUrl = getRandomProblemUrl(difficulty, website);
            const audio = new Audio(browser.runtime.getURL('ding.mp3'));
            audio
              .play()
              .catch((error) => console.error('Audio playback failed:', error));
            resolve({ redirectUrl: redirectUrl });
          }
        },
      );
    });
  },
  { urls: ['*://*.facebook.com/*'] },
  ['blocking'],
);
